# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sidebar2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bodyFrame = QtWidgets.QFrame(self.centralwidget)
        self.bodyFrame.setGeometry(QtCore.QRect(0, 0, 937, 720))
        self.bodyFrame.setStyleSheet("QFrame{background-color: rgb(0, 255, 0);\n"
"box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );\n"
"backdrop-filter: blur( 4.5px );\n"
"-webkit-backdrop-filter: blur( 4.5px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );} ")
        self.bodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bodyFrame.setObjectName("bodyFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.bodyFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.bodyFrame)
        self.icon_only_widget.setStyleSheet("QWidget{background: rgba( 255, 255, 255, 0.7 );\n"
"box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );\n"
"backdrop-filter: blur( 4.5px );\n"
"-webkit-backdrop-filter: blur( 4.5px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );} ")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeBtn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.homeBtn_1.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 3px solid rgb(37, 255, 3); color: rgb(0, 0, 0); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.homeBtn_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn_1.setIcon(icon)
        self.homeBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.homeBtn_1.setCheckable(True)
        self.homeBtn_1.setAutoExclusive(True)
        self.homeBtn_1.setObjectName("homeBtn_1")
        self.verticalLayout.addWidget(self.homeBtn_1)
        self.addUbtn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.addUbtn_1.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 3px solid rgb(37, 255, 3); color: rgb(0, 0, 0); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.addUbtn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/addU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addUbtn_1.setIcon(icon1)
        self.addUbtn_1.setIconSize(QtCore.QSize(40, 40))
        self.addUbtn_1.setCheckable(True)
        self.addUbtn_1.setAutoExclusive(True)
        self.addUbtn_1.setObjectName("addUbtn_1")
        self.verticalLayout.addWidget(self.addUbtn_1)
        self.addFbtn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.addFbtn_1.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 3px solid rgb(37, 255, 3); color: rgb(0, 0, 0); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.addFbtn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/addF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFbtn_1.setIcon(icon2)
        self.addFbtn_1.setIconSize(QtCore.QSize(40, 40))
        self.addFbtn_1.setCheckable(True)
        self.addFbtn_1.setAutoExclusive(True)
        self.addFbtn_1.setObjectName("addFbtn_1")
        self.verticalLayout.addWidget(self.addFbtn_1)
        self.postsBtn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.postsBtn_1.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 3px solid rgb(37, 255, 3); color: rgb(0, 0, 0); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.postsBtn_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/posts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.postsBtn_1.setIcon(icon3)
        self.postsBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.postsBtn_1.setCheckable(True)
        self.postsBtn_1.setAutoExclusive(True)
        self.postsBtn_1.setObjectName("postsBtn_1")
        self.verticalLayout.addWidget(self.postsBtn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 295, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.exitBtn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exitBtn_1.setMinimumSize(QtCore.QSize(69, 49))
        self.exitBtn_1.setMaximumSize(QtCore.QSize(50, 50))
        self.exitBtn_1.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 3px solid rgb(37, 255, 3); color: rgb(0, 0, 0); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.exitBtn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn_1.setIcon(icon4)
        self.exitBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.exitBtn_1.setObjectName("exitBtn_1")
        self.verticalLayout_3.addWidget(self.exitBtn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.bodyFrame)
        self.full_menu_widget.setStyleSheet("QWidget{background: rgba( 255, 255, 255, 0.7 );\n"
"box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );\n"
"backdrop-filter: blur( 4.5px );\n"
"-webkit-backdrop-filter: blur( 4.5px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );} ")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_3.setStyleSheet("QLabel{ color: rgb(0, 255, 0)}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.homeBtn_2.setStyleSheet("QPushButton{color: rgb(0, 255, 0)}\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px; text-transform: uppercase; }\n"
"QPushButton:pressed{color: white;}\n"
"                                           ")
        self.homeBtn_2.setIcon(icon)
        self.homeBtn_2.setIconSize(QtCore.QSize(25, 25))
        self.homeBtn_2.setCheckable(True)
        self.homeBtn_2.setAutoExclusive(True)
        self.homeBtn_2.setObjectName("homeBtn_2")
        self.verticalLayout_2.addWidget(self.homeBtn_2)
        self.addUbtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.addUbtn_2.setStyleSheet("QPushButton{color: rgb(0, 255, 0)}\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px; text-transform: uppercase; }\n"
"QPushButton:pressed{color: white;}\n"
"                                           ")
        self.addUbtn_2.setIcon(icon1)
        self.addUbtn_2.setIconSize(QtCore.QSize(25, 25))
        self.addUbtn_2.setCheckable(True)
        self.addUbtn_2.setObjectName("addUbtn_2")
        self.verticalLayout_2.addWidget(self.addUbtn_2)
        self.addFbtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.addFbtn_2.setStyleSheet("QPushButton{color: rgb(0, 255, 0)}\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px; text-transform: uppercase; }\n"
"QPushButton:pressed{color: white;}\n"
"                                           ")
        self.addFbtn_2.setIcon(icon2)
        self.addFbtn_2.setIconSize(QtCore.QSize(25, 25))
        self.addFbtn_2.setCheckable(True)
        self.addFbtn_2.setAutoExclusive(True)
        self.addFbtn_2.setObjectName("addFbtn_2")
        self.verticalLayout_2.addWidget(self.addFbtn_2)
        self.postsBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.postsBtn_2.setStyleSheet("QPushButton{color: rgb(0, 255, 0)}\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px; text-transform: uppercase; }\n"
"QPushButton:pressed{color: white;}\n"
"                                           ")
        self.postsBtn_2.setIcon(icon3)
        self.postsBtn_2.setIconSize(QtCore.QSize(25, 25))
        self.postsBtn_2.setCheckable(True)
        self.postsBtn_2.setAutoExclusive(True)
        self.postsBtn_2.setObjectName("postsBtn_2")
        self.verticalLayout_2.addWidget(self.postsBtn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 397, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.exitBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exitBtn_2.setStyleSheet("QPushButton{color: rgb(0, 255, 0)}\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px; text-transform: uppercase; }\n"
"QPushButton:pressed{color: white;}\n"
"                                           ")
        self.exitBtn_2.setIcon(icon4)
        self.exitBtn_2.setIconSize(QtCore.QSize(25, 25))
        self.exitBtn_2.setObjectName("exitBtn_2")
        self.verticalLayout_4.addWidget(self.exitBtn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.bodyFrame)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setStyleSheet("QWidget{background: rgba( 255, 255, 255, 0.7 );\n"
"box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );\n"
"backdrop-filter: blur( 4.5px );\n"
"-webkit-backdrop-filter: blur( 4.5px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );} ")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.changeBtn = QtWidgets.QPushButton(self.widget)
        self.changeBtn.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.changeBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changeBtn.setIcon(icon5)
        self.changeBtn.setIconSize(QtCore.QSize(30, 30))
        self.changeBtn.setCheckable(True)
        self.changeBtn.setObjectName("changeBtn")
        self.horizontalLayout_4.addWidget(self.changeBtn)
        spacerItem2 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBar = QtWidgets.QLineEdit(self.widget)
        self.searchBar.setStyleSheet("QLineEdit{color: rgb(0, 255, 0)}\n"
"")
        self.searchBar.setObjectName("searchBar")
        self.horizontalLayout.addWidget(self.searchBar)
        self.searchBtn = QtWidgets.QPushButton(self.widget)
        self.searchBtn.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 5px; }\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.searchBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchBtn.setIcon(icon6)
        self.searchBtn.setIconSize(QtCore.QSize(20, 20))
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.profileBtn = QtWidgets.QPushButton(self.widget)
        self.profileBtn.setStyleSheet("QPushButton{  color: rgb(37, 255, 3); border-radius: 10px; }\n"
"QPushButton:hover{ border: 2px solid rgb(37, 255, 3); border-radius: 10px }\n"
"QPushButton:pressed{ background-color: rgb(0, 0, 0); color: rgb(37, 255, 3); }\n"
"                                           ")
        self.profileBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileBtn.setIcon(icon7)
        self.profileBtn.setIconSize(QtCore.QSize(30, 30))
        self.profileBtn.setObjectName("profileBtn")
        self.horizontalLayout_4.addWidget(self.profileBtn)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setStyleSheet("QWidget{background: black; border-radius: 10px}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.homePage = QtWidgets.QLabel(self.page)
        self.homePage.setStyleSheet("QLabel{ background: rgba( 255, 255, 255, 0.7 );\n"
"box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );\n"
"backdrop-filter: blur( 4.5px );\n"
"-webkit-backdrop-filter: blur( 4.5px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );}")
        self.homePage.setText("")
        self.homePage.setPixmap(QtGui.QPixmap("C:/Users/arrey/Downloads/speak (1).png"))
        self.homePage.setScaledContents(True)
        self.homePage.setObjectName("homePage")
        self.gridLayout_3.addWidget(self.homePage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setGeometry(QtCore.QRect(210, 120, 351, 361))
        self.frame.setStyleSheet("QFrame{background: rgba( 255, 255, 255, 0.7 );\n"
"box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );\n"
"backdrop-filter: blur( 4.5px );\n"
"-webkit-backdrop-filter: blur( 4.5px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );} ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addFpage = QtWidgets.QLabel(self.page_3)
        self.addFpage.setStyleSheet("QLabel{ border: 2px solid rgb(0, 255, 0); color: white;}")
        self.addFpage.setObjectName("addFpage")
        self.gridLayout_4.addWidget(self.addFpage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.postsPage = QtWidgets.QLabel(self.page_4)
        self.postsPage.setStyleSheet("QLabel{ border: 2px solid rgb(0, 255, 0); color: white;}")
        self.postsPage.setObjectName("postsPage")
        self.gridLayout_5.addWidget(self.postsPage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.changeBtn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.changeBtn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.homeBtn_1.toggled['bool'].connect(self.homeBtn_2.setChecked) # type: ignore
        self.addUbtn_1.toggled['bool'].connect(self.addUbtn_2.setChecked) # type: ignore
        self.addFbtn_1.toggled['bool'].connect(self.addFbtn_2.setChecked) # type: ignore
        self.postsBtn_1.toggled['bool'].connect(self.postsBtn_2.setChecked) # type: ignore
        self.homeBtn_2.toggled['bool'].connect(self.homeBtn_1.setChecked) # type: ignore
        self.addUbtn_2.toggled['bool'].connect(self.addUbtn_1.setChecked) # type: ignore
        self.addFbtn_2.toggled['bool'].connect(self.addFbtn_1.setChecked) # type: ignore
        self.postsBtn_2.toggled['bool'].connect(self.postsBtn_1.setChecked) # type: ignore
        self.exitBtn_2.clicked.connect(MainWindow.close) # type: ignore
        self.exitBtn_1.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "SPEAK"))
        self.homeBtn_2.setText(_translate("MainWindow", "  Home"))
        self.addUbtn_2.setText(_translate("MainWindow", "  Users"))
        self.addFbtn_2.setText(_translate("MainWindow", "  Friends"))
        self.postsBtn_2.setText(_translate("MainWindow", "  Posts"))
        self.exitBtn_2.setText(_translate("MainWindow", "  Exit"))
        self.searchBar.setPlaceholderText(_translate("MainWindow", "Search.."))
        self.addFpage.setText(_translate("MainWindow", "ADD FRIENDS"))
        self.postsPage.setText(_translate("MainWindow", "POSTS"))
import resources_rc
